services:
  db:
    image: postgres:16
    container_name: booking_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d booking_app" ]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:7
    container_name: booking_redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      timeout: 5s

  booking:
    image: booking_image
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env
    command: [ "/booking/docker/start_app.sh" ]
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  celery:
    image: booking_celery
    build:
      context: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    container_name: booking_celery
    command: [ "/booking/docker/start_celery.sh", "celery" ]
    depends_on:
      redis:
        condition: service_healthy

  flower:
    image: booking_flower
    build:
      context: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    container_name: booking_flower
    command: [ "/booking/docker/start_celery.sh", "flower" ]
    ports:
      - 5555:5555
    depends_on:
      redis:
        condition: service_healthy
      celery:
        condition: service_started

  prometheus:
    image:
      prom/prometheus:v3.1.0
    container_name: booking_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.5.1
    container_name: booking_grafana
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgresdata:
  grafanadata:
  prometheusdata:
